# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, cairo, dataDefault, gtk, mtl, time }:

cabal.mkDerivation (self: {
  pname = "tellme";
  version = "0.1.0.0";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  buildDepends = [ cairo dataDefault gtk mtl time ];
  meta = {
    description = "Status bar for Xmonad etc";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
